version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: product-postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
